version: '3'

services:
  wehavesecrets:
    image: wehavesecrets
    build:
      context: ./WeHaveSecrets
      dockerfile: Dockerfile

  db.wehavesecrets.setup:
    image: db.wehavesecrets.setup
    build:
      context: ./Db.WeHaveSecrets.Setup
      dockerfile: Dockerfile
