version: '3'

services:
  web:
    build: 
      context: ../WeHaveSecrets
    ports:
      - 8080:80
    volumes:
      - ${WEHAVESECRETS_WORKINGFOLDER}/backups:/app/wwwroot/backups
    environment:
      "ConnectionStrings:DefaultConnection": "Server=db;Database=WeHaveSecrets;User Id=sa;Password=${WEHAVESECRETS_SQLPASSWORD};" 
    depends_on:
      - db

  db:
    image: microsoft/mssql-server-linux:latest
    ports:
      - ${WEHAVESECRETS_SQLLOCALPORT}:1433
    volumes:
      - ${WEHAVESECRETS_WORKINGFOLDER}/backups:/app/wwwroot/backups
    environment:
      ACCEPT_EULA: ${WEHAVESECRETS_SQLLICENCEACCEPTED}
      SA_PASSWORD: ${WEHAVESECRETS_SQLPASSWORD}

  db-setup:
    build: 
      context: ../Db.WeHaveSecrets
    environment:
      "CONNECTIONSTRING": "Server=db;Database=WeHaveSecrets;User Id=sa;Password=${WEHAVESECRETS_SQLPASSWORD};" 
    depends_on:
      - db

  tests-end2end:
    image: redfolder/wehavesecrets-end2endtests
    volumes:
      - ${WEHAVESECRETS_WORKINGFOLDER}/end2end/videos:/app/cypress/videos
      - ${WEHAVESECRETS_WORKINGFOLDER}/end2end/screenshots:/app/cypress/screenshots
    environment:
      WEHAVESECRETS_URL: "http://web"
    depends_on:
      - web

  teamcity-server:
    image: jetbrains/teamcity-server
    ports:
     - "8111:8111"

  teamcity-agent-dotnet:
    image: jkleczkowski/teamcity-agent-dotnet-core
    environment:
      SERVER_URL: http://teamcity-server:8111
      AGENT_NAME: dotnet
      WEHAVESECRETS_WORKINGFOLDER: ${WEHAVESECRETS_WORKINGFOLDER}
      WEHAVESECRETS_SQLLOCALPORT: ${WEHAVESECRETS_SQLLOCALPORT}
      WEHAVESECRETS_SQLPASSWORD: ${WEHAVESECRETS_SQLPASSWORD}
      WEHAVESECRETS_SQLLICENCEACCEPTED: ${WEHAVESECRETS_SQLLICENCEACCEPTED}
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - teamcity-server

  teamcity-agent-compose:
    image: redfolder/teamcity-agent-docker-compose
    environment:
      SERVER_URL: http://teamcity-server:8111
      AGENT_NAME: compose
      WEHAVESECRETS_WORKINGFOLDER: ${WEHAVESECRETS_WORKINGFOLDER}
      WEHAVESECRETS_SQLLOCALPORT: ${WEHAVESECRETS_SQLLOCALPORT}
      WEHAVESECRETS_SQLPASSWORD: ${WEHAVESECRETS_SQLPASSWORD}
      WEHAVESECRETS_SQLLICENCEACCEPTED: ${WEHAVESECRETS_SQLLICENCEACCEPTED}
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - teamcity-server

