version: '3'

services:
  teamcity-server:
    image: jetbrains/teamcity-server
    ports:
     - "8111:8111"
    networks:
      secrets-network:
        ipv4_address: 172.20.0.20

  teamcity-agent1:
    image: jkleczkowski/teamcity-agent-dotnet-core
    environment:
      SERVER_URL: http://teamcity-server:8111
      AGENT_NAME: agent1
      WEHAVESECRETS_WORKINGFOLDER: ${WEHAVESECRETS_WORKINGFOLDER}
      WEHAVESECRETS_SQLLOCALPORT: ${WEHAVESECRETS_SQLLOCALPORT}
      WEHAVESECRETS_SQLPASSWORD: ${WEHAVESECRETS_SQLPASSWORD}
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    networks:
      secrets-network:
        ipv4_address: 172.20.0.21

  db:
    image: microsoft/mssql-server-linux:latest
    ports:
      - ${WEHAVESECRETS_SQLLOCALPORT}:1433
    environment:
      ACCEPT_EULA: ${WEHAVESECRETS_SQLLICENCEACCEPTED}
      SA_PASSWORD: ${WEHAVESECRETS_SQLPASSWORD}
    volumes:
     - ${WEHAVESECRETS_WORKINGFOLDER}/backups:/app/wwwroot/backups
    networks:
      secrets-network:
        ipv4_address: 172.20.0.22
networks:
  secrets-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
